### ISSUE TITLE
reduce the number of recent records in the rss feed

### ISSUE THREAD

**Issue by logston** [pyvideo/pyvideo#10]
> Hi
> I tried to add your RSS feed to online rss reader (theoldreader) and couldn't. Their answer is:
> "The reason you cannot add this feed is because it is way too large. The file is nearly 7MB and takes almost 30 seconds to fetch.
> RSS feeds are intended only to keep the most recent posts, not all posts. I'm sure the site's owner would prefer this as well, as they don't want to pay for all of that data transfer."
> Can you please reduce the number of recent records in the feed?

**Comment by zerok** [comment]
Should we simply set `FEED_MAX_ITEMS` to 30?

**Comment by logston** [comment]
That sounds great.

**Comment by zerok** [comment]
Will try that either tonight or until Sunday then :)
