### ISSUE TITLE
PyData Paris 2015 videos

### ISSUE THREAD

**Issue by sfermigier** [pyvideo/pyvideo#101]
All the videos have been posted to youtube: <https://www.youtube.com/watch?v=E3p2gX67oBA&list=PLzjFI0G5nSsqCLCRa-Iyh5G_yIFn-Bw9G>.

We can help by providing the proper metadata. Tell us how to proceed.

Also, given that the proximity with PyCon US, maybe it's a good thing to wait a bit before adding the collection to Pyvideo..

**Comment by codersquid** [comment]
Thanks @sfermigier, it was easy for me to scrape the data from the channel, but please go through and make sure I didn't get the wrong information on anything. One didn't have speaker info so I found their names by hand.

http://pyvideo.org/category/66/pydata-paris-2015

I don't think it's too soon to post the collection. If @willkg disagrees I can flip the videos back to draft mode and they won't show up.

**Comment by willkg** [comment]
I'm totally fine with putting videos on pyvideo as soon as someone gets to them. I don't think we have to wait for the glow to recede from the latest set.

**Comment by codersquid** [comment]
@sfermigier I clicked around in a few videos and they were English but I haven't watched them all. If any are French please let me know and I'll update the language description.

**Comment by codersquid** [comment]
I'll close this now. If I missed anything, please reopen.

**Comment by sfermigier** [comment]
Thanks, everything seems fine to me. The talks are in english, indeed.
