### ISSUE TITLE
PyConZA 2012, 2013 and 2014 videos

### ISSUE THREAD

**Issue by hodgestar** [pyvideo/pyvideo#102]
Videos are available at Archive.org:

- [ ] 2012: https://archive.org/search.php?query=pyconza2012
- [ ] 2013: http://archive.org/search.php?query=pyconza2013
- [x] 2014: https://archive.org/search.php?query=pyconza2014

These should have good metadata, but in case you need more you can look at the talk lists for the three years:

* 2012: http://2012.za.pycon.org/schedule.html
* 2013: http://2013.za.pycon.org/talks/
* 2014: http://2014.za.pycon.org/talks/

Thanks for mantaining pyvideo.org!

**Comment by hodgestar** [comment]
I wrote a script for reading video metadata from archive.org and converting it to pyvideo.org format.

I've gist the output from PyConZA 2014. Would you mind having a look at it and checking whether it is suitable for uploading? The gist is at https://gist.github.com/hodgestar/c3152a2310e183b258bd.

Mostly for my own records: The file was generated with `python ao2pyv.py "PyConZA 2014" pyconza2014 pyconza2014-pyv.json --output json_file`. See https://github.com/hodgestar/ao2pyv for the script.

**Comment by hodgestar** [comment]
Gist for PyConZA 2014 has been updated to properly set the language and ao2pyv has been cleaned up a bit and released on PyPI.

**Comment by codersquid** [comment]
@hodgestar thanks for all of the help. I've got 2014 up, http://www.pyvideo.org/category/75/pycon-za-2014 please let me know if you see problems with it.

I ended writing some one-off code to get the ogg, mp4, and thumbnails for the pyvideo json. I checked our api doc, and I realize those fields are not documented! I apologize. I made a note about it on the wiki page and included an example link for illustration.

This is throw away code, but you can see how I populated the fields you don't have yet.
https://gist.github.com/codersquid/e7b5237c397b0fcd6662

When I do the other years, I may make a pull request for your package to include those fields as well.

**Comment by hodgestar** [comment]
Thank you for the putting up the PyConZA 2014 videos!

I've updated my script to add the video links and made JSON files for 2012 and 2013:

* https://gist.github.com/hodgestar/55cd412c0b71f496c111 (2012)
* https://gist.github.com/hodgestar/7b6ff682fabc1bd15ea7 (2013)

I didn't add the `whiteboard` field because I didn't really understand what a sensible way was.

If you prefer, you should be able to use your script with the searches `subject:pyconza2012` and `subject:pyconza2013` instead.

**Comment by codersquid** [comment]
http://pyvideo.org/category/78/pycon-za-2013 and 
http://pyvideo.org/category/79/pycon-za-2012

**Comment by hodgestar** [comment]
Thank you!
