### ISSUE TITLE
Pyvec - videos from Czech user groups

### ISSUE THREAD

**Issue by encukou** [pyvideo/pyvideo#106]
Hello,
Videos from Czech Python meetups (in Prague, Brno and Ostrava) are added to this account when (and if -- volunteer time is short) they're made available: https://www.youtube.com/user/pyvec

Most are in Czech.

**Comment by honzajavorek** [comment]
Note: Some videos from Brno are also at https://www.youtube.com/channel/UCzE1AyBbdp8_fbDvnrW5GgA. If it would be easier to track only one channel, we could probably merge it somehow - just let us know.
