### ISSUE TITLE
Pythology Lecture Series: Data Science with Python

### ISSUE THREAD

**Issue by calvinhp** [pyvideo/pyvideo#109]
This is the playlist from the latest installment of our IndyPy quarterly event.

https://www.youtube.com/playlist?list=PLt4L3V8wVnF5IU4YPgBgf9nokGOysCb1o

Thanks!
Calvin

**Comment by calvinhp** [comment]
Any word on this?  Is this still the correct process?

**Comment by codersquid** [comment]
This is still the correct process. I've been volunteering for multiple orgs this year and spent a few months focusing on my hackerspace.
