### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by natea** [pyvideo/pyvideo#110]
The video on this page doesn't seem to load properly:
http://pyvideo.org/video/35/djangocon-2010--lightning-talks---day-1

**Comment by natea** [comment]
It appears that this is the 511MB file associated with the video:
http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/djangocon-2010/35_lightning-talks-day-1.flv

**Comment by willkg** [comment]
What do you mean by "doesn't seem to load properly"?

**Comment by CarlFK** [comment]
both of these, the player just shows the spinning wheel circle:

http://pyvideo.org/video/35/djangocon-2010--lightning-talks---day-1
http://pyvideo.org/video/56/djangocon-2010--customizing-the-django-admin

I didn't try any others from djangocon-2010

this does play:
mplayer
http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/djangocon-2010/56_customizing-the-django-admin.flv


On Mon, May 25, 2015 at 6:47 PM, Will Kahn-Greene <notifications@github.com>
wrote:

> What do you mean by "doesn't seem to load properly"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/110#issuecomment-105338072>.
>



-- 
Carl K
