### ISSUE TITLE
Search broken (access control)

### ISSUE THREAD

**Issue by nkantar** [pyvideo/pyvideo#110]
When trying to search I get the following errors in my browser console:

> GET https://api.pyvideo.org/v1/search?q=Guido 502 ()
> Failed to load https://api.pyvideo.org/v1/search?q=Guido: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://pyvideo.org' is therefore not allowed access. The response had HTTP status code 502.

Looks like CORS isn't set properly?

**Comment by zerok** [comment]
Hi :) The backend service is sadly acting up a little bit. I've tried restarting it but, sadly, it looks like it will require a bit more force. I've contacted @ulope :)

**Comment by redapple** [comment]
@zerok , I don't know much about this, but has a pure JavaScript solution been envisaged?
e.g. https://github.com/olivernn/lunr.js/ or http://elasticlunr.com/ so that the search index could be built at the same time as the static pages.
Just my 2 cents.

**Comment by ulope** [comment]
Search is up again. Thanks for the ping @zerok. The container was up but hung in a non recoverable state. I had some other (very resource hungry) things running on the same server and apparently docker doesn't recover well from having little to no memory left. I'll add "memory free" to the monitoring to avoid this in the future.

@redapple In theory that would be nice. Unfortunately, the search index is > 700MB so this is not an option.

**Comment by nkantar** [comment]
Seems to be resolved. 😄
