### ISSUE TITLE
pycon SE (Sweden) 2015 had at least one interesting talk in english

### ISSUE THREAD

**Issue by stonebig** [pyvideo/pyvideo#114]
https://www.youtube.com/watch?v=Niq-HoraNPo

**Comment by codersquid** [comment]
Thanks for the heads up!

We should add the entire conference, not just English talks. We do that for other conferences.

here's the channel.
https://www.youtube.com/channel/UCH_2cuWzFMyCPvm75lJJ6wg

**Comment by codersquid** [comment]
Done http://pyvideo.org/category/70/pycon-se-2015 (they made it easy by having descriptions and speaker info on the youtube pages!)

**Comment by stonebig** [comment]
thanks !

**Comment by stonebig** [comment]
you have also missed Pycon FR 2013, by the way: https://www.youtube.com/channel/UC1KLo7CmIYsCnA1_hVk4QhQ

the "PyConFR 2013 - Marc Chantreux - du beau code Perl" was a great moment

**Comment by willkg** [comment]
@stonebig Please open up a separate issue for that.
