### ISSUE TITLE
missed Pycon FR 2013 (that looks nicely present on youtube)

### ISSUE THREAD

**Issue by stonebig** [pyvideo/pyvideo#115]
https://www.youtube.com/channel/UC1KLo7CmIYsCnA1_hVk4QhQ

the "PyConFR 2013 - Marc Chantreux - du beau code Perl" was a great moment

I didn't find equivalent links for the 2014 edition.
2015 edition is later this year

**Comment by codersquid** [comment]
Hi, I have added http://pyvideo.org/category/73/pycon-fr-2013 please check through for any problems and reopen this if you find them.
