### ISSUE TITLE
PyCon PL 2013 and 2014

### ISSUE THREAD

**Issue by Unit03** [pyvideo/pyvideo#117]
Videos from PyCon PL 2013 and 2014 are available at https://www.youtube.com/user/pyconpl channel :)

2013 edition has playlists:
* talks: https://www.youtube.com/playlist?list=PL2Eaz-sXg3mX8lWj7XIekPNvNRgu9NMsT
* lightning talks: https://www.youtube.com/playlist?list=PL2Eaz-sXg3mWGbsGONsw0U3q1aByLJlXR

2014 unfortunately not.

Can I help with indexing them?

**Comment by CarlFK** [comment]
Can you add a feature to the conference site to provide an api to the data
behind

http://pl.pycon.org/2014/en/agenda

Something like
http://www.pyohio.org/schedule/json/





On Sat, Jul 11, 2015 at 7:19 AM, Unit03 <notifications@github.com> wrote:

> Videos from PyCon PL 2014 are available at
> https://www.youtube.com/user/pyconpl channel :)
>
> Can I help with indexing them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/117>.
>



-- 
Carl K

**Comment by Unit03** [comment]
> Can you add a feature to the conference site to provide an api to the data behind http://pl.pycon.org/2014/en/agenda

No, 'cause I don't manage the site, but I can provide analogous JSON: https://gist.github.com/Unit03/ea230a8098a1171a3c5f 

Remarks:
* I wasn't sure what `kind` value to use for workshops, so I just went with `workshop` :)
* I used `null` in `released` for similar reason
* as talks on PyCon PL are about in half in Polish language, I've added `language` field with ISO-639-1 language code

How can I improve it further for you?

Also, that's for 2014 only, would you want 2013 version as well?

**Comment by CarlFK** [comment]
That's fine. It has the authors.

2013 would be great.

also if you have the youtube URLs handy, add them.
otherwise we have to get the list of video titles from youtub and find the
similar

 "name": "Creating interactive visualizations with Bokeh",

which sometimes isn't so easy.





On Sun, Jul 12, 2015 at 8:40 AM, Unit03 <notifications@github.com> wrote:

> Can you add a feature to the conference site to provide an api to the data
> behind http://pl.pycon.org/2014/en/agenda
>
> No, 'cause I don't manage the site, but I can provide analogous JSON:
> https://gist.github.com/Unit03/ea230a8098a1171a3c5f
>
> Remarks:
>
>    - I wasn't sure what kind value to use for workshops, so I just went
>    with workshop :)
>    - I used null in released for similar reason
>    - as talks on PyCon PL are about in half in Polish language, I've
>    added language field with ISO-639-1 language code
>
> How can I improve it further for you?
>
> Also, that's for 2014 only, would you want 2013 version as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/117#issuecomment-120721404>.
>



-- 
Carl K

**Comment by Unit03** [comment]
I'll take care of 2013 and YouTube links, stay tuned. :)

**Comment by Unit03** [comment]
Done:
* 2013: https://gist.github.com/Unit03/2d069f65020c441373e0
* 2014: https://gist.github.com/Unit03/ea230a8098a1171a3c5f

Few remarks:
* videos of only 36 out of ~60 agenda entries from 2014 were published
* 2013's lightning talks agenda entries/YT videos provide almost no metadata (title, description) - I didn't include them
* one talk from 2013 is on YT, but not on agenda on the website - I used info from YT (datetimes and room are missing)

**Comment by codersquid** [comment]
@CarlFK said he could work on this one by importing things in to veyepar and pushing up the data.
