### ISSUE TITLE
Typo in "Orgins" on http://www.pyvideo.org/video/3659/some-things-ive-made-with-django

### ISSUE THREAD

**Issue by simonw** [pyvideo/pyvideo#118]
The title is "Django Orgins (and some things I have built with Django)" - it should be "Django Origins (and some things I have built with Django)

http://www.pyvideo.org/video/3659/some-things-ive-made-with-django

**Comment by CarlFK** [comment]
fixed.

On Tue, Jul 14, 2015 at 5:01 PM, Simon Willison <notifications@github.com>
wrote:

> The title is "Django Orgins (and some things I have built with Django)" -
> it should be "Django Origins (and some things I have built with Django)
>
> http://www.pyvideo.org/video/3659/some-things-ive-made-with-django
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/118>.
>



-- 
Carl K
