### ISSUE TITLE
SciPy 2015

### ISSUE THREAD

**Issue by sstugk** [pyvideo/pyvideo#120]
List of talks:
* Title + Speakers: http://www.scipy2015.scipy.org/ehome/115969/292868/?&
* Title + Speakers + Description: http://scipy2015.scipy.org/ehome/115969/292269/?&

YouTube playlist of talks:
* https://www.youtube.com/playlist?list=PLYx7XA2nY5Gcpabmu61kKcToLz0FapmHu

**Comment by codersquid** [comment]
@sstugk, is there a chance that you have well structured data for the talks? I've scraped them but the css/html on the page is inconsistent and the results from the scrape aren't all accurate.

**Comment by sstugk** [comment]
Unfortunately not. I myself stumbled on these videos by chance. I stand in no direct relation to the organizers.

Maybe you can make use of the detail pages for sessions and speakers. (presented via Iframes and triggered by the Javascript calls to `load_url(...)` when clicking on "[More Info]" or some speaker names on http://www.scipy2015.scipy.org/ehome/115969/292868/?&) 

For example, the plans for the "Astropy in 2015" talks hide here:
```
http://www.scipy2015.scipy.org/ereg/popups/sessiondetails.php?eventid=115969&sessionid=7417458&sessionchoice=1&&
```

While the speaker details are accessible via:
```
http://www.scipy2015.scipy.org/ereg/popups/speakerdetails.php?eventid=115969&language=eng&speakerid=281474&&
```

The HTML structure seems to be fairly consistent.

Let me know if you could use any help.

**Comment by codersquid** [comment]
@sstugk Would you like to take a stab at scraping up titles, speakers, and descriptions for me? I was in the middle of doing this but had to switch context to other stuff.

Here is the unknown current state of things. https://gist.github.com/codersquid/50ba13d8c36fc203822a

Ignore the `steve` parts of the code. I was getting some inaccuracies from scraped code. notably when there are multiple speakers, and also when a speaker has a link versus not a link.

**Comment by elliewix** [comment]
Here's a gist with all the session links, but posters are included: https://gist.github.com/elliewix/1ac9150c6e1b7682df21

**Comment by bheklilr** [comment]
I've been looking forward to these talks making it onto the site, is anyone still working on this or can I volunteer?

**Comment by sstugk** [comment]
Hi people,

please excuse the delay. I had crazy issues with my harddrive. Now that I have my data back, I've time to share with you what I've wrote in a bit spare time.

The solution is quick and dirty. I put everything in the `__main__` section and don't cared for your framework. (Sorry for that, I was a bit in a hurry.)

You can find the code here: https://gist.github.com/sstugk/67a3f3af8f6fa9f1891c

I reused the URLs, @elliewix has collected and included the posters since they were presented too and have according videos in the Youtube playlist. The urls need to reside in `./data/scipytalklinks.txt`. (relative to the current working directory)

Every thing else is stored there as well. I've put all the data (links, raw html data of the talks and the parsed data in JSON format) here: https://www.dropbox.com/s/8zau6ad92f1p9gu/data.zip?dl=0

You can just skip the download and parsing steps I've implemented by unzipping the archive in the current working directory.

*What remains?*
The data includes title, description and names of the authors. For each author there can be found some extra details in the `speakerdetails.php` pages, e.g.: http://www.scipy2015.scipy.org/ereg/popups/speakerdetails.php?eventid=115969&speakerid=281474&language=eng&back=1
I din't include that, but the speaker details are formatted in the same way as the talk details. Thus, it shouldn't be that hard to fetch them as well.

*Note:* I have used the `pattern` package. You can install it via `pip`.

Hope I could help you.

**Comment by sstugk** [comment]
Ahh, I've overseen the Youtube playlist. :sweat_smile: I just fixed this and updated
- the gist (https://gist.github.com/sstugk/67a3f3af8f6fa9f1891c)
  and
- the data (https://www.dropbox.com/s/8zau6ad92f1p9gu/data.zip?dl=0).

I've used the Youtube Data API, so you'll need an API key to reconstruct the results in `data.zip`. (Anyway, the complete API response is in `./data/youtube_playlist.json`.)

*Additional notes:*

1. The homepage data and the Youtube playlist diverge a bit. This means:
   - There are Youtube videos not listed on the homepage. These are especially the keynotes, lightning talks and tutorials. I've not checked if there are any other types of talks in the playlist which are not present on the homepage.
   - There are talks (or poster sessions) on the homepage without corresponding video in the playlist.
   I manually checked some of them and could verify that (in these cases) this is not due to errors. There is simply no video. In other cases there may be a video the script didn't recognize. (see point 3 in this list)

2. The authors data of the talks is a bit inconsistent, this means:
    Any video found in the Youtube playlist and not contained in the data from the homepage has no
   author link. This means not that there is no one. There may be other talks of this speaker with the
   corresponding link present.
   (Just now I see, that the term *author* in the code and the JSON data is a bit misleading. Clearly,
    with author I mean *speaker*.)
3. Youtube seems to have restrictions on title length. Thus, some speaker names or even titles were cut off. E.g.:
   - *"Widgets and Astropy Accomplishing Productive Research with Undergraduates | SciPy 2015 | Matthew Cr"*
  - *"A Distributed, Standards Based Framework for Searching, Accessing, Analyzing and Visualizing Met Oce"*

   This also applies only to talks found in the Youtube playlist and not contained in homepage data.
- The matching of Youtube titles against homepage titles failed in one case. (see code comments) I've fixed this by hand. The complete dataset is in `./data/talks_fixed.json`

That's all. :smile:
