### ISSUE TITLE
EuroPython 2015

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#121]
I found the EuroPython channel, and need to check for all the videos.
https://www.youtube.com/user/PythonItalia/videos

**Comment by codersquid** [comment]
Right now they have videos with multiple talks in them. I don't know if anyone is going to split them up.

**Comment by codersquid** [comment]
I emailed the contact address for europython to see if they will be able to split out talks.

**Comment by codersquid** [comment]
I got a really nice response to my email! There is a person in charge of handling uploads of individual talks, and he is able to work with us to give us the data and links we need.

:sparkles: :octopus: :bouquet:  :sparkles:

**Comment by redapple** [comment]
I think this is the YouTube playlist you're looking for: https://www.youtube.com/playlist?list=PL8uoeex94UhGGUH0mFb-StlZ1WYGWiJfP

**Comment by codersquid** [comment]
@redapple Probably correct. Anton from the organizers is uploading the videos and will be providing some json for us that we can use to push the data to pyvideo. That way we won't need to resort to scraping the playlist.

It is pretty awesome that he's doing this for us! He's going to give us the json data mentioned in the [for advanced users](https://github.com/pyvideo/pyvideo/wiki/Suggesting-videos-for-the-site#for-advanced-users) section.

**Comment by AvdN** [comment]
I sent an email with the metadata today. The data include an archive_url field which points to where the data was uploaded to archive.org (the video_url points to the instance on youtube).

**Comment by redapple** [comment]
hello @codersquid , any updates on EuroPython 2015 videos and the metadata from @AvdN?

**Comment by codersquid** [comment]
Hi @redapple I don't have any updates. Sorry about that! I've had some busy months.

**Comment by redapple** [comment]
I understand @codersquid . If you need a hand, let me know.
