### ISSUE TITLE
PyOhio 2010 and 2011 have borked data

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#122]
http://pyvideo.org/category/11/pyohio-2010

http://pyvideo.org/category/12/pyohio-2011

I'm not sure what happened with these. @carlfk might have data for these that might make it easy to fix, I can't remember if this was something from the bliptvpolypse or what.

**Comment by CarlFK** [comment]
bummer.  I have 2012 and on.

It is possible there never was good data.


On Tue, Jul 28, 2015 at 2:11 PM, Sheila Miguez <notifications@github.com>
wrote:

> http://pyvideo.org/category/11/pyohio-2010
>
> http://pyvideo.org/category/12/pyohio-2011
>
> I'm not sure what happened with these. @carlfk <https://github.com/carlfk>
> might have data for these that might make it easy to fix, I can't remember
> if this was something from the bliptvpolypse or what.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/122>.
>



-- 
Carl K

**Comment by willkg** [comment]
We might have saved PyOhio 2010 and 2011 from blip.tv in which case they
have whatever meh data we could salvage from blip.tv.

On Tue, Jul 28, 2015, at 03:18 PM, Carl Karsten wrote:
> bummer.  I have 2012 and on.
>
>
It is possible there never was good data.
>
>
>
On Tue, Jul 28, 2015 at 2:11 PM, Sheila Miguez
<notifications@github.com>
>
wrote:
>
>
> http://pyvideo.org/category/11/pyohio-2010
>
>
>
> http://pyvideo.org/category/12/pyohio-2011
>
>
>
> I'm not sure what happened with these. @carlfk
> <https://github.com/carlfk>
>
> might have data for these that might make it easy to fix, I can't
> remember
>
> if this was something from the bliptvpolypse or what.
>
>
>
> —
>
> Reply to this email directly or view it on GitHub
>
> <https://github.com/pyvideo/pyvideo/issues/122>.
>
>
>
>
>
>
-- 
> 
Carl K
> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/pyvideo/pyvideo/issues/122#issuecomment-125725295
