### ISSUE TITLE
Djangocon Europe 2015 videos are up.

### ISSUE THREAD

**Issue by qasimalbaqali** [pyvideo/pyvideo#127]
https://vimeo.com/channels/952478/135738762

**Comment by codersquid** [comment]
Hi @qasimalbaqali by any chance are you associated with the conference? I'd like to know if I can get metadata from you.

**Comment by codersquid** [comment]
http://2015.djangocon.eu/talks/ looks reasonably scrapable and at first glance they seem to have used the same titles in the vimeo page.

**Comment by elliewix** [comment]
I went ahead and scraped that out and have a csv of it. Can I attach a file here...? Or should I just email?

**Comment by codersquid** [comment]
@elliewix that is fantastic.

Here's the gist, for reference. https://gist.github.com/codersquid/9cb25fce7d8d64af81a4

**Comment by qasimalbaqali** [comment]
@codersquid hey sorry for the late reply, no I am not associated with the conference. Was checking pyvideos yesterday and noticed that the Djangocon EU was not added since a lot of people were looking forward to the release of the videos and thought I would give the heads up :)
