### ISSUE TITLE
PyCon AU 2015

### ISSUE THREAD

**Issue by za** [pyvideo/pyvideo#128]
Starting this [video](https://www.youtube.com/watch?v=NheE6udjfGI) it was PyCon AU **2015**. Can you add these videos? 

Many thanks!

**Comment by za** [comment]
@codersquid Oh, they sorted the video into the [playlist](https://www.youtube.com/user/PyConAU/playlists). 

The miniconfs are: 

* Django
* Education
* OpenStack
* Science and Data

**Comment by za** [comment]
@codersquid Hi, is there anything I could help to make these videos available from pyvideo?

**Comment by za** [comment]
Hi there! I'll be happy to help if there's something I could do...

**Comment by codersquid** [comment]
@za I've been swamped with work, sorry for taking so long! I haven't looked through all the playlists yet, do you know if the PyCon Australia 2015 playlist has everything including the ones in the smaller playlists?

**Comment by codersquid** [comment]
Hi @za, I scraped the PyCon Australia 2015 playlist and the videos are up here, http://pyvideo.org/category/80/pycon-au-2015 could you help by taking a look to check for errors? I haven't checked the smaller playlists to see if they are included yet.

**Comment by za** [comment]
@codersquid thanks a lot! I'll have a look tonight.

**Comment by za** [comment]
Hi @codersquid , I manually count on videos that were added 2 months ago. There are 93 videos. There are some duplicates (and private video) on the playlist. While the videos that are added to pyvideo is 60.

**Comment by willkg** [comment]
@za Can you make a list of urls for the videos that are missing?

**Comment by za** [comment]
@willkg ok, will do.

**Comment by za** [comment]
@willkg there you go, the 33 missing videos link. cc @codersquid 

https://www.youtube.com/watch?v=0FOQB4PZVe0
https://www.youtube.com/watch?v=1ABPQyANid0
https://www.youtube.com/watch?v=1KHM7WvNeL4
https://www.youtube.com/watch?v=2e9dMr5sErs
https://www.youtube.com/watch?v=6aSKs4_WdkI
https://www.youtube.com/watch?v=8BUuq0KVXm0
https://www.youtube.com/watch?v=9yiiwcntx5M
https://www.youtube.com/watch?v=BiFUDT4aGFk
https://www.youtube.com/watch?v=HhcotmeioT8
https://www.youtube.com/watch?v=Ie7XdxTL5MY
https://www.youtube.com/watch?v=JG8-yurFBXM
https://www.youtube.com/watch?v=LPfMlOBB5VQ
https://www.youtube.com/watch?v=N_Q3i3oaZ6w
https://www.youtube.com/watch?v=NheE6udjfGI
https://www.youtube.com/watch?v=QFPtArm4Wc0
https://www.youtube.com/watch?v=SGleKfigMsk
https://www.youtube.com/watch?v=YYzJdxI_g6g
https://www.youtube.com/watch?v=YkVscKsV_qk
https://www.youtube.com/watch?v=ZS9CRzgLNCE
https://www.youtube.com/watch?v=_HZR7_ZBkYY
https://www.youtube.com/watch?v=aSRk0L6D3Zs
https://www.youtube.com/watch?v=ccFqbCwcLko
https://www.youtube.com/watch?v=cnX5MGmWpXg
https://www.youtube.com/watch?v=eox2gqRlqZU
https://www.youtube.com/watch?v=gOnnjPQzXg8
https://www.youtube.com/watch?v=gaFk0Sya_HI
https://www.youtube.com/watch?v=h0ISxOv9JE0
https://www.youtube.com/watch?v=k7hSD_-gWMw
https://www.youtube.com/watch?v=kGJVDOaBkKU
https://www.youtube.com/watch?v=of6pHdSbtOM
https://www.youtube.com/watch?v=pIh7G8RG6JM
https://www.youtube.com/watch?v=q86LUTxCDPg
https://www.youtube.com/watch?v=tl0wkY78jk4

**Comment by za** [comment]
This is the gist https://gist.github.com/za/43424a7d0762d3f1687c

**Comment by za** [comment]
Hi @codersquid @willkg let me know if there's something I could help!

**Comment by codersquid** [comment]
Hi @za, thanks for the help. I've added the videos to the category on pyvideo now. There were two videos for Rapid Prototyping with Teenagers. Raise an alert if I've linked the wrong one. http://pyvideo.org/video/4058/rapid-prototyping-with-teenagers

**Comment by za** [comment]
Hi @codersquid 

Thanks a lot for adding those videos! 

I think I know why it has two videos. From the PyCon AU 2015 website, they were the same talk but at the different time (I think it was repeated). I saw Katie Bell, the speaker, was introduced by the different person. 

* Friday schedule
http://2015.pycon-au.org/schedule/30116/view_talk?day=friday

* Sunday schedule
http://2015.pycon-au.org/schedule/30116/view_talk?day=sunday

So, that's why they have two youtube videos there:

* https://www.youtube.com/watch?v=gOnnjPQzXg8
* https://www.youtube.com/watch?v=h0ISxOv9JE0
