### ISSUE TITLE
PyCon ZA 2014

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#130]
@hodgestar hopped in to irc to let us know about data they have made available for this conference

https://gist.github.com/hodgestar/c3152a2310e183b258bd

which btw I think is all under this pyconza2014 tag on archive.org
https://archive.org/search.php?query=subject%3A%22pyconza2014%22

**Comment by hodgestar** [comment]
This might be considered a duplicate of https://github.com/pyvideo/pyvideo/issues/102 but this ticket is more focused, so maybe worthwhile keeping both.

**Comment by codersquid** [comment]
I'm closing it as a duplicate. thanks!
