### ISSUE TITLE
Add the videos from DjangoCon US 2015

### ISSUE THREAD

**Issue by elbaschid** [pyvideo/pyvideo#136]
DjangoCon US 2015 in Austin, Texas was recorded by ConFreaks and videos are available at: http://confreaks.tv/events/djangocon2015.

It would be great if those videos could be added 😎.

**Comment by codersquid** [comment]
Looks like they have it up on youtube too, which is good since we have scraper code for youtube. https://www.youtube.com/watch?v=dBeXS5aFLNc&list=PLE7tQUdRKcyaRCK5zIQFW-5XcPZOE-y9t

**Comment by codersquid** [comment]
With schedule data here https://2015.djangocon.us/schedule/json/

**Comment by CarlFK** [comment]
Why do I only see 6 talks?

 curl https://2015.djangocon.us/schedule/json/ | jsonlint -f | grep name

    "name" : "Hello Web App: Build your First Web App with Django",
    "name" : "Don't be afraid to search",
    "name" : "Documenting your project with Sphinx and Read the Docs",
    "name" : "Building a REST API Using Django & Django REST Framework",
    "name" : "Lightning Talks",
    "name" : "Lightning Talks",



On Mon, Oct 19, 2015 at 1:46 PM, Sheila Miguez <notifications@github.com>
wrote:

> With schedule data here https://2015.djangocon.us/schedule/json/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/136#issuecomment-149309694>.
>



-- 
Carl K

**Comment by codersquid** [comment]
Huh, I guess I can't use the json endpoint.
