### ISSUE TITLE
Add PyTexas 2015 Videos

### ISSUE THREAD

**Issue by pizzapanther** [pyvideo/pyvideo#137]
Please add the PyTexas 2015 videos which took place in College Station, TX this year.

Data here: https://www.pytexas.org/api/v1/speakers/pyvideo?conf=2015

Most are up on YouTube already.  I think we still have a few in the upload process still but the data on API should be updated when they are completed.  Thanks :-)

**Comment by codersquid** [comment]
I had a little bump with this due to an issue with steve. I've pushed 29 videos (draft mode, so you can't see them yet). Do you have any more to post?

**Comment by pizzapanther** [comment]
Thought we would have one or two more uploads but we haven't.  So the current API data is good.

**Comment by codersquid** [comment]
On Mon, Oct 26, 2015 at 10:15 AM, Paul Bailey <notifications@github.com>
wrote:

> Thought we would have one or two more uploads but we haven't. So the
> current API data is good.


Okiedokie. Once I have some time I can sanity check the videos and flip
them from draft to live.


-- 
shekay@pobox.com

**Comment by pizzapanther** [comment]
Thanks!

On Mon, Oct 26, 2015, 10:24 AM Sheila Miguez <notifications@github.com>
wrote:

> On Mon, Oct 26, 2015 at 10:15 AM, Paul Bailey <notifications@github.com>
> wrote:
>
> > Thought we would have one or two more uploads but we haven't. So the
> > current API data is good.
>
>
> Okiedokie. Once I have some time I can sanity check the videos and flip
> them from draft to live.
>
>
> --
> shekay@pobox.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/137#issuecomment-151173115>.
>
-- 
Twitter: PizzaPanther
Phone: 409-233-3339
