### ISSUE TITLE
Paris-Saclay Center for Data Science - Open Software Initiative (OSI) day (2015-10-26), Starring Fernando Perez

### ISSUE THREAD

**Issue by stonebig** [pyvideo/pyvideo#139]
http://webcast.in2p3.fr/videos-keynote_speech__jupyter_at_bids_building_the_tools_and_the_institutions_for_data_science

**Comment by redapple** [comment]
@stonebig , would you have the original video files somewhere on http://webcast.in2p3.fr/?
I can only see RTSP stream URLs.

Links like http://webcast.in2p3.fr/content/videos/00/66/87/Loic.Esteve.mp4 or http://webcast.in2p3.fr/00/66/87/Loic.Esteve.mp4 for http://webcast.in2p3.fr/videos-mining_brain_imaging_data_lessons_learned_from_nilearn_and_joblib do not work even if the markup has the following

```
<input type="hidden" id="current_video_path" name="current_video_path" value="/00/66/87/Loic.Esteve.mp4" />
```

**Comment by stonebig** [comment]
well, in the mean time I discover also that :
- the videos are only registered on my left (or left-right) sound track, so I don't here it with a right-only headphone,
- I can't read them with a Windows phone.
==>  I propose we close this issue and give up.

**Comment by codersquid** [comment]
Fine with me to close given what you have discovered. :( Sorry about that.
