### ISSUE TITLE
PyCon France (Oct 2015) - videos posted:  http://video-pyconfr2015.paulla.asso.fr/

### ISSUE THREAD

**Issue by Dowwie** [pyvideo/pyvideo#144]
talks were finally posted:  http://video-pyconfr2015.paulla.asso.fr/

**Comment by redapple** [comment]
FTR,
I've started collecting metadata for the recorded talks: https://github.com/redapple/pyvideo-contrib/tree/master/pyconfr2015/pyconfr2015

- [`talks.json`](https://raw.githubusercontent.com/redapple/pyvideo-contrib/master/pyconfr2015/pyconfr2015/talks.json) is scraped from http://www.pycon.fr/2015/schedule/
- [`videos.json`](https://raw.githubusercontent.com/redapple/pyvideo-contrib/master/pyconfr2015/pyconfr2015/videos.json) is scraped from http://video-pyconfr2015.paulla.asso.fr/

Next: reconcile both sources to match `richard` format

**Comment by redapple** [comment]
@codersquid ,

I created JSON files for all videos, following steve format the best I could:

https://github.com/redapple/pyvideo-contrib/tree/master/pyconfr2015/pyconfr2015-steve/json

Let me know if this works.

I also posted the [ipython notebook](https://github.com/redapple/pyvideo-contrib/blob/master/pyconfr2015/pyconfr2015/mergedata.ipynb) I used to merge the scraped data and video duration usign `ffprobe`

I believe all videos are in French (I didn't check all), except [Charlie Clark's](https://github.com/redapple/pyvideo-contrib/blob/master/pyconfr2015/pyconfr2015-steve/json/009___Charlie_Clark___The_Art_of_Doing_Nothing___Using_profiling_to_speed_up_your_code.json) which was in English
