### ISSUE TITLE
pyvideo.org search not returning recent items.

### ISSUE THREAD

**Issue by purplediane** [pyvideo/pyvideo#146]
Search doesn't seem to be searching the whole database. A few days ago I searched for `pdb` and got a nice list of videos about pdb. I gave the results link (`http://pyvideo.org/search.html?q=pdb`) to my students as a reference for videos about pdb. 
Today that link comes up empty. A number of other searches also come up empty, like `iterator`, for example. Searches that get any results don't seem to have anything more recent than 2014, like `pandas`.

**Comment by logston** [comment]
Sorry to hear that @purplediane and thanks for letting us know!

**Comment by zerok** [comment]
@ulope Seems like the disk is full on that server. Could you please take a look and restart the search service? Thanks 😄

**Comment by ulope** [comment]
@zerok Thanks for the heads up. Apparently, my monitoring still isn't working properly :(

The disk is now purged, the index re-created, the service is running again and returning results.

However during re-indexing I noticed quite a few errors in the log relating to unexpected date formats. I'll open a separate issue for that.

**Comment by zerok** [comment]
@ulope : Thanks! I will take a look ASAP.
