### ISSUE TITLE
Search: broken results because of different link generation from slugs

### ISSUE THREAD

**Issue by redapple** [pyvideo/pyvideo#185]
@zerok , continuing the discussion in https://github.com/pyvideo/data/issues/584

It looks like the indexing is not using the same slugs to build the URLs to point to the correct event or video pages.

Example:
- with the query "reactjs", that DjangoCon EU 2016 video _"Django and ReactJS: The good, the bad and the ugly"_ from Tomáš Ehrlich is found, but the links are wrong:
  - the talk link generated as
    `https://pyvideo.org/djangocon-eu-2016/django-and-reactjs-the-good-the-bad-and-the-ugly.html`;
    while the video is available at
    `https://pyvideo.org/djangocon-europe-2016/django-and-reactjs-the-good-the-bad-and-the-ugly.html` (if you go to [the event page](https://pyvideo.org/events/djangocon-europe-2016.html))
  - the event page from that search result is `https://pyvideo.org/events/djangocon-eu-2016.html` while the correct one is `https://pyvideo.org/events/djangocon-europe-2016.html`

I believe it's because of the slugs used for the talk's `data/` folder vs. the slug from the conference title

**Comment by zerok** [comment]
Ah, so the conference slug is using a different algo. Will try to look into it this weekend.

**Comment by zerok** [comment]
With some luck it's fixed now with https://github.com/zerok/pyvideosearch/commit/6c93c11fc945dba6dd10096abea3fc7de21f928e 🙂
