### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by douglance** [pyvideo/pyvideo#202]
It would be great to be able to sort the videos by popularity, views, likes, or some other metric. There's so much content and videos are so long, that it's difficult to find really high quality videos.

**Comment by logston** [comment]
Hi @douglance, thanks for the suggestion and I recognize that it can be somewhat hard to find a video based on its popularity.

However, at this time, a rating system would be contradictory to our Why and to our Development Philosophy. 

- https://pyvideo.org/pages/about.html
- https://github.com/pyvideo/pyvideo/wiki/Development-Philosophy#new-features

I encourage you to use whatever resources we have available and that you find useful to build out the solution you are looking for.

**Comment by douglance** [comment]
Oh interesting. Did not realize that was the idea behind the site. I will build a system myself. Thanks for the information!
