### ISSUE TITLE
Pycon 2019 Keynote video link returns 404

### ISSUE THREAD

**Issue by jackiekazil** [pyvideo/pyvideo#214]
When I search for Russell's PyCon Keynote, I get these results: https://pyvideo.org/search.html?q=Russell 

When I click on the first link, it takes me here: https://pyvideo.org/pycon-us-2019/russell-keith-magee-keynote-pycon-2019.html ... which returns a 404. 

Not sure what is happening there, but wanted to put it on your radar.

**Comment by jonafato** [comment]
Thank you for this report. This specific talk issue has been fixed. The linked issue about search results generating invalid links is still a problem, and further work will follow there.
