### ISSUE TITLE
thank you and archiving

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo#239]
I just archived a few of the repositories related to the previous incarnation of pyvideo. Just wanted to let you know it was me. If any of them are still in use, kick me and I can un-archive them. Also, if there are others that should get archived, we should archive them, too.

Thank you all so much for continuing on pyvideo! I appreciate it so much! It's a project @codersquid and I spent a lot of time on and it's fantastic you all have kept it going and improved on it in so many ways. Thank you!

**Comment by redapple** [comment]
Thank you for everything @willkg
