### ISSUE TITLE
Configure Travis-CI to run tests once a week or even once a day 

### ISSUE THREAD

**Issue by szabgab** [pyvideo/pyvideo#254]
The tests in Travis-CI have failed in all 3 of my pull-requests. It seems regardless to what the changes were.  It seems something has changed in the environment since the most recent build 6 days ago.

Travis can be configured to run the job once a day (or once a week) even without any push/PR.
Enabling this could help noticing such external changes soon after they happen.

**Comment by redapple** [comment]
The errors you saw in Travis have already been reported in https://github.com/pyvideo/pyvideo/issues/117
It's more related to who opens the PR than the environment

**Comment by jonafato** [comment]
CI is now on GitHub Actions rather than TravisCI.
