### ISSUE TITLE
Where is the source of api.pyvideo.org ?

### ISSUE THREAD

**Issue by szabgab** [pyvideo/pyvideo#260]
In order to implement #252 I'd either do it in JavaScript post-processing the search results, or
in the back-end search engine.
However I could not find a reference to where the source of api.pyvideo.org can be found or any explanation how that works. Have I missed it? Could you share links and explanations?

**Comment by zerok** [comment]
You can find the search backend here: https://github.com/zerok/pyvideosearch 🙂

**Comment by szabgab** [comment]
Awesome. Thanks.
I've added a link to it to the wiki page: https://github.com/pyvideo/pyvideo/wiki/Search-API
Could you include a few words on where and how does it run in production, please? Either on the wiki page or in the README.md of the Search-API?
