### ISSUE TITLE
Rackspace suspension warning for pyvideo rackspace account

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#267]
Hi all,

It's been forever since I logged in to the email account that was used for the old pyvideo account on rackspace that was sponsored by them. I logged in today and found a suspension warning for that account because it started getting billed in January. I've got a January bill for 171.10 and a February bill for $473.84. The previous months are 0.

Are pyvideo files still stored in that account? If so, could someone work out sponsorship details? I've left a message on the ticket mentioning that it was a sponsored account, but that sponsorship was started so long ago that I do not know if they  have a record for it.

I know they've turned off the sponsorship before by mistake, but that was so long ago that I'm not sure I could find the email or whatever exchange.

anyway, HELP.

**Comment by codersquid** [comment]
Ugh I went through old (closed) tickets and saw one from a couple of months ago.

> Upon review we noted your account had been receiving the Open Compute Discount in 2019. Regrettably, Rackspace will no longer be able to offer this discount effective as of December 31st, 2019. Rackspace does however have commitment discounts available at the following percentages and term lengths below:

**Comment by redapple** [comment]
@logston would probably know if we have anything in Rackspace.
I would say no, but I can't be sure.

**Comment by codersquid** [comment]
A lot of earlier videos might be linked to rackspace content. I think at some point someone may have been mirroring them on archive.org, but I have no idea what is going on these days.

Perhaps @CarlFK knows.

**Comment by ewdurbin** [comment]
Hi! I'm Director of Infrastructure at the Python Software Foundation.

What is currently being hosted at Rackspace and being billed for? If there's a need to move resources quickly out of Rackspace the PSF infra may be able to absorb them temporarily (or long term depending on what the need is).

As far as the billed costs go I hope that Rackspace is able to understand and support PyVideo, but in case they are not I'm going to share this issue with the PSF board to give them a heads up on the situation.

**Comment by codersquid** [comment]
The majority of the bill is for some cloud servers. Cloud files and CDN backup are next, but less.

I think @CarlFK uses the cloud servers for machine that process videos he makes at python conferences (and other open source events).

I am extremely out of the loop. The account is going to get suspended, I do not know what that will take down.

I do not want to be the owner of this account anymore. I've asked Carl to take it over since it runs his servers.

**Comment by ewdurbin** [comment]
If any of the pyvideo.org infra needs a place to land, please let me know!

**Comment by codersquid** [comment]
When I do a search in the pyvideo/data repo for rackcdn I get a huge number of hits.

There are containers here, and one is called pyvideo.
![containers](https://user-images.githubusercontent.com/529748/76899965-8117e080-6866-11ea-9b91-027304123cde.png)

**Comment by ewdurbin** [comment]
Wrote this quick script to scan the pyvideo/data repo:

```python
#!/usr/bin/env python3
  
import glob
import json

for video_json in glob.glob('**/videos/*.json'):
    with open(video_json) as f:
        data = json.loads(f.read())
        if any(['rackcdn' in v['url'] for v in data['videos']]):
            print(f"Rackspace CDN URL found for {data['slug']}")
            print(f"  Alternative Sources:")
            for video in data['videos']:
                if 'rackcdn' not in video['url']:
                    print(f"   - {video['type']}: {video['url']}")
```

Full Results: https://gist.github.com/ewdurbin/81f32403f7488b400e1f3d59bdbf87b6

Slightly modified:

```python
#!/usr/bin/env python3
  
import glob
import json

for video_json in glob.glob('**/videos/*.json'):
    with open(video_json) as f:
        data = json.loads(f.read())
        if any(['rackcdn' in v['url'] for v in data['videos']]):
            if len([v['url'] for v in data['videos'] if 'rackcdn' not in v['url']]) == 0:
                print(f"Rackspace CDN URL found for {data['slug']}")
                print(f"  No Alternative Sources found!")
```

It appears there are two videos that are in the dataset, but don't have anything but pyvideo hosting them:

```
Rackspace CDN URL found for pyconau-2010--using-python-in-a-scientific-real-t
  No Alternative Sources found!
Rackspace CDN URL found for pyconau-2010--getting-started-with-apache-mod-wsg
  No Alternative Sources found!
```

**Comment by codersquid** [comment]
Ok, then I think things are safe with closing this once someone handles those two files. Worse case scenario, no one does and they get lost. I'm currently too swamped to handle them.

**Comment by logston** [comment]
Very big thank you to everyone on this thread. Here are the two videos that could be lost by ending our Rackspace partnership. 

http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/pycon-au-2010/463_pyconau-2010-using-python-in-a-scientific-real-time-data-collection-network.flv

http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/pycon-au-2010/468_pyconau-2010-getting-started-with-apache-mod-wsgi.flv

I've downloaded both so feel free to close the account @codersquid. 

As for rehosting, I'm in the process now of moving them to archive.org. I'll post again once they are up.

**Comment by logston** [comment]
Looks like they are already up on Archive.org!

- https://archive.org/details/pyvideo_468___pyconau-2010-getting-started-with-apache-mod-wsgi
- https://archive.org/details/pyvideo_463___pyconau-2010-using-python-in-a-scientific-real-time-data-collection-network

They just need to be integrated into the data repo.

**Comment by logston** [comment]
These two PRs should fix this issue:

- https://github.com/pyvideo/data/pull/1008
- https://github.com/pyvideo/data/pull/1009
