### ISSUE TITLE
Hosting a peertube instance?

### ISSUE THREAD

**Issue by JulienPalard** [pyvideo/pyvideo#281]
Here at AFPy we produce some videos (PyConFr, montly meetups, ...), and are trying to find proper and multiple ways to host them, so [currently we do use](https://github.com/pyvideo/data/blob/55ba73c57a4e72040c8e02d909fd9cdc818e369d/en-attendant-pyconfr-2020-2021/videos/dessine-moi-une-tortue-antoine-entwanne-rozo.json):

- dl.afpy.org: a simple machine we host, exposing a simple directory listing, old school, functional.
- Youtube
- A "random" Peertube instance

We're searching for a way to enhance this, and we think having a [peertube](https://joinpeertube.org/en/) instance dedicated to Python videos would be a great way to enhance both our process and pyvideo.

I personally don't think having an AFPy instance make sense: we're too little.

The PSF like the idea, but would prefer not hosting it. The next obvious / legitimate place would be pyvideo.

What do you think?

**Comment by logston** [comment]
Hey @JulienPalard, thanks for the suggestion. I have a few questions. 

1. Who would be accountable for running the instance? 
2. Would all pyvideo videos live there? 
3. Are you suggesting the video links default to peertube? 
4. Would we remove the youtube/etc links from this repo? 
5. Has there been any issue with the current setup that PyVideo has? Or is this an effort to consolidate python video hosting in one place? 
6. Do you imagine pyvideo logic would still be used to search the contents of the peer tube instance or would a new search tool be needed? 

Thanks!

**Comment by JulienPalard** [comment]
>     1. Who would be accountable for running the instance?

This is a good question, I'm just throwing the idea without an answer to this question, I'm really not aware of the "sysadmin workforce of PyVideo".

>     2. Would all pyvideo videos live there?

I have no opinion on this, there's pros and cons of hosting all videos (like the ability to find all videos from peertube search engine and https://sepiasearch.org/).

>     3. Are you suggesting the video links default to peertube?

From an end user privacy (and advertising invasion? I don't know if youtube push ads on PyVideo) point of view, linking by default to a self-hosted peertube instance is better than linking to Youtube.

The player look like a normal player, see: https://pyvideo.org/en-attendant-la-pyconfr-2020-2021/hydra.html.

>     4. Would we remove the youtube/etc links from this repo?

Same, I have no opinion on this. In one hand I don't think we should remove other links: my initial goal is to provide more (not less) ways for users to upload and view the videos, giving the choice. In the other hand, if PyVideo staff really don't like Youtube, it's a way to drop it.

>     5. Has there been any issue with the current setup that PyVideo has? Or is this an effort to consolidate python video hosting in one place?

No issues, the current state of PyVideo is already very nice: the ability to link to a simple video file (like [here](https://pyvideo.org/en-attendant-la-pyconfr-2020-2021/hydra.html)) already partially solve the choice problem: it's solved for organizers having a server to host videos, which is not always the case.

>     6. Do you imagine pyvideo logic would still be used to search the contents of the peer tube instance or would a new search tool be needed?

I think having a PyVideo Peertube instance don't change pyvideo.org at all, it's just one more link for videos that happen to also be hosted on the PyVideo's peertube instance. Users could also browse the videos from the peertube instance, and by doing so use the peertube instance search engine.


Those questions highlight a thing: there's two extreme ways to see it, and a whole gradient of solutions in between, ranging from replacing pyvideo.org by a peertube instance to just allowing uploaders to "upload to pyvideo" when they feel/need/want it without changing a single line of code in pyvideo.org.

**Comment by ewdurbin** [comment]
Just to add some context, if the PyVideo project decides to take on the maintenance of a peer tube instance, the PSF Infrastructure can support it as a financial and support backstop assuming that estimated costs are reasonable.

Once a decision is made we can work out the details.

**Comment by logston** [comment]
Thanks @JulienPalard. Pardon the delay in response as this is a small team and all volunteer. 

Although the solution of a hosting a peertube instance sounds interesting, it ultimately sounds like more work than I think PyVideo can handle. PyVideo turned towards a very low maintenance model many years back and I believe its success and endurance since is largely attributed to that choice. It's just too much to ask of PyVideo volunteers to run more than a static site. That is [by design](https://github.com/pyvideo/pyvideo/wiki/Development-Philosophy#new-features) and not a comment on the engineers' abilities.

Thank you for bringing this solution to us. But at this time we are going to need to pass.

**Comment by logston** [comment]
@ewdurbin, Thanks for the offer!

**Comment by JulienPalard** [comment]
Thanks @logston for your answer.

As a big fan of static sites, I can only understand and approve your choices here.

While I'm here, I recently discovered the "Other events in this series" feature in https://pyvideo.org/events/pycon-fr-2019.html, which is very nice! Thanks for the amazing job you're doing with pyvideo!
