### ISSUE TITLE
404 on FastAPI PyCascades 2021 Talk

### ISSUE THREAD

**Issue by dougBelcher** [pyvideo/pyvideo#282]
Got a 404 on the link to a FastAPI talk by Aaron Bassett for PyCascades 2021 
https://pyvideo.org/pycascades-2021/introducing-the-farm-stack-fastapi-react-mongodb-aaron-bassett-pycascades-2021.html

**Comment by di** [comment]
Looks like the entire PyCascades 2021 event is not showing: https://pyvideo.org/events/pycascades-2021.html is 404 as well, and 2021 is not listed here: https://pyvideo.org/events.html

**Comment by di** [comment]
Looks like search is separate from the website itself, and the `data` directory hasn't been updated since April: https://github.com/pyvideo/pyvideo/commit/f24e9153bb684d840eb35df285f2028523243c09
