### ISSUE TITLE
IP change for api.pyvideo.org

### ISSUE THREAD

**Issue by zerok** [pyvideo/pyvideo#291]
Hey :) To the person who has DNS access for pyvideo.org: Could you please change the IP for api.pyvideo.org from 46.101.212.176 to 142.132.191.121 ? I did some server-moving and would like to deprovision the old server :) 

The search server is already running on the new host but LetsEncrypt might require a couple of loops before the cert can get verified :)

**Comment by logston** [comment]
Done! Thanks @zerok!!!

**Comment by zerok** [comment]
Awesome, thank you very much, Paul! I couldn't find your e-mail address anymore 🤣
