### ISSUE TITLE
Broken link in search results

### ISSUE THREAD

**Issue by staeff** [pyvideo/pyvideo#293]
The talk "Logging and Exception Handling for Django" by Ryan Sullivan (DjangoCon US 2019) has a faulty link in the search results. It is the first hit on this page https://pyvideo.org/search.html?q=Logging+and+Exception+Handling+for+Django

The link used in this search result is "https://pyvideo.org/djangocon-us-2019/-logging-and-exception-handling-for-django.html", but the correct link would be "https://pyvideo.org/djangocon-us-2019/logging-and-exception-handling-for-django.html" (not starting with a dash).

The linking on the speaker page and the conference listing is correct.

**Comment by zerok** [comment]
Hi :) I will try to find some time for this in the next couple of days :)

**Comment by zerok** [comment]
Ahhh, there is an extra space in the JSON file :) Will strip that for the slug generation.

**Comment by staeff** [comment]
Fantastic, I had no idea were to look for the problem 👍
