### ISSUE TITLE
Several (Two) events per year?

### ISSUE THREAD

**Issue by andife** [pyvideo/pyvideo#296]
How can I link a series of events, when there are more than one event a year?
For example: 2022_06, 2021_10, 2021_03 (Year_month)
Which file do I've to change/adjust?

**Comment by logston** [comment]
Hi @andife, that's a good question. We don't really have a set way of doing that at this time. 

The closest we have is groups that have may events per year. For example, the [Minsk Python Meetup](https://github.com/pyvideo/data/tree/fd733eab402966f234d61bcfbef19d7a656a0e67/minsk-python-meetup).

You might look at them for their layout for direction. 

As for files to adjust, I think you would only need to add new video reference files to the event directory as they become available. 

Please reopen if that does not answer your question.
