### ISSUE TITLE
Add "Python Web Conf 2022" talks

### ISSUE THREAD

**Issue by asweigart** [pyvideo/pyvideo#299]
The link to the "Python Web Conf 2022" event at https://pyvideo.org/events/python-web-conf-2022.html leads to a 404 error.

All talks for this event seem to also be 404, including:

https://pyvideo.org/python-web-conf-2022/origami.html

https://pyvideo.org/python-web-conf-2022/lightning-talk-datetime-vs-datetime.html

https://pyvideo.org/python-web-conf-2022/lightning-talk-from-markdown-to-blog-with-markata.html

**Comment by logston** [comment]
Oh no! Thank you for bring this to my attention. I'll try to address this later this week.

**Comment by logston** [comment]
Hi @asweigart, it looks like there is no Web Conf 2022. 
<img width="1624" alt="Screenshot 2023-01-09 at 16 42 06" src="https://user-images.githubusercontent.com/2641765/211436383-bf877a09-00a1-41e0-8432-8d9a9870ea5f.png">
<img width="981" alt="Screenshot 2023-01-09 at 16 42 57" src="https://user-images.githubusercontent.com/2641765/211436393-54e74f43-2897-4b03-8649-5d160b3f91bf.png">

Was 2022 ever added?

**Comment by logston** [comment]
Can you let me know where you got that link? https://pyvideo.org/events/python-web-conf-2022.html I'm not convinced it ever existed.

**Comment by asweigart** [comment]
Ack! I've forgotten. Most likely from the conference's website. They have a link to their own playlist with all the 2022 videos here: https://www.youtube.com/playlist?list=PLt4L3V8wVnF7PJ3wfq1rdJWX4ziasHMHl

**Comment by logston** [comment]
Got it. I'm going to update the title then of this ticket to reflect the changes required.

**Comment by jonafato** [comment]
It looks like this was fixed in #300. https://pyvideo.org/events/python-web-conf-2022.html now shows the event's videos.
