### ISSUE TITLE
Search for pyvideo

### ISSUE THREAD

**Issue by logston** [pyvideo/pyvideo#3]
See https://github.com/pytube/pytube/issues/165

**Comment by zerok** [comment]
@EricSchles are you still working on this? 😃

**Comment by EricSchles** [comment]
As of right now, no.  I wasn't sure how to proceed with the server stuff.  I've got working code, but only locally.

**Comment by zerok** [comment]
@EricSchles How far have you come? 

@ulope and I were also thinking about perhaps looking into hosted solution like Algolia so that we wouldn't have to manage our own search servers but only needed a rather thin server-component.

Depending on the stage you're in we would abort that research ;)

**Comment by ulope** [comment]
Just to expand a bit on that: We met some people from Algolia at WriteTheDocs Europe and they told us that they provide their services for free to open source projects.

**Comment by logston** [comment]
Closing this as it doesn't have the traction it needs.
