### ISSUE TITLE
404

### ISSUE THREAD

**Issue by logston** [pyvideo/pyvideo#61]
Reported by Krishnan Narayanan

![unnamed](https://cloud.githubusercontent.com/assets/2641765/24530698/b0fe6e12-1581-11e7-8fa4-8528ff6b85e8.png)

**Comment by Daniel-at-github** [comment]
How Krishnan Narayanan get from http://pyvideo.org/index.html to http://pyvideo.org/category/50/pycon-us-2014 ?
The usual path is http://pyvideo.org/index.html :arrow_forward: http://pyvideo.org/events.html :arrow_forward: http://pyvideo.org/events/pycon-us-2014.html

Looked for it in the pyvideo repo:
~~~ bash
git pull upstream master
make html
find -type d | egrep "/50/|/pycon-us-2014"
~~~
no luck
~~~
./output/video/50/djangocon-2010--treehugging
./output/pycon-us-2014
./data/pycon-us-2014
./data/pycon-us-2014/videos
~~~

**Comment by willkg** [comment]
That looks like an old PyVideo url. Doing a google search on that url brings up a bunch of places where it shows up.

**Comment by Daniel-at-github** [comment]
Now I get it (https://github.com/pyvideo/data/blob/master/pycon-us-2014/category.json)
~~~ json
{
  "alias": "category/50/PyCon-US-2014",
  "description": "PyCon is the largest annual gathering for the community using and\ndeveloping the open-source Python ....\n",
  "title": "PyCon US 2014"
}
~~~
this alias is not working.

**Comment by jonafato** [comment]
It seems that the `alias` attribute never worked for categories, but this is fixed with some recent generator and data changes.
