### ISSUE TITLE
enable search of tags and other data

### ISSUE THREAD

**Issue by zevaverbach** [pyvideo/pyvideo#66]
other data could include transcripts/captions that exist for some videos.

**Comment by zerok** [comment]
#3 was just about that an recently closed due to lack of activity. That being said, I would love to sprint on it at PyCon if nobody minds 😊Due to the input size and tooling I have in mind right now, the actual implementation might end up being in Go.

**Comment by zerok** [comment]
I've now created a separate repository for the search backend on https://github.com/zerok/pyvideosearch and will now work on adding a frontend for that in the main pyvideo code-base.

**Comment by zerok** [comment]
The current implementation now does full-text search for sessions over title, description, speaker names etc. I've a dummy implementation now running locally:

![screenshot 2017-05-22 14 34 21](https://cloud.githubusercontent.com/assets/3782/26329396/ee6b32e6-3efb-11e7-9918-3666bc5dec83.png)

I hope, this looks OK for you. If you don't mind then I'd host a search index on one of my servers. @logston : Could you perhaps please add a a DNS entry for api.pyvideo.org pointing to 46.101.212.176 ? I'd then add a TLS cert there and push my code either later today or tomorrow (if my laptop survives that long 😞 ) :)

**Comment by logston** [comment]
DNS Done!

**Comment by zerok** [comment]
@logston Thank you :) I will try to get a prototype up and running including a PR for the front-end changes by noon 😃

**Comment by ulope** [comment]
Hey @logston, unfortunately it turns out @zerok's vserver doesn't have enough ram to rebuild the index inplace, so we've moved the api to one of my servers. For now we're forwarding the requests via nginx but it would be nicer to update the DNS to directly point to the correct IP.

Could you update the records for api.pyvideo.org to `45.76.95.160` / `2001:19f0:6c01:3d3:5400:ff:fe62:f743`?

**Comment by logston** [comment]
Done!

**Comment by zerok** [comment]
Thank you :D


On Fri, May 26, 2017, at 05:24 PM, Paul wrote:
> Done!


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/pyvideo/pyvideo/issues/66#issuecomment-304311705
