### ISSUE TITLE
EuroPython 2013

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo#70]
We added EuroPython 2014 videos, but I never got around to adding EuroPython 2013 videos last year.

The url provided in the suggestion is this one:

http://www.youtube.com/user/PythonItalia/videos?shelf_index=4&sort=dd&tag_id=&view=0

This issue covers adding that conference.

**Comment by malemburg** [comment]
This URL is the playlist for EuroPython 2013:

https://www.youtube.com/playlist?list=PL8uoeex94UhF5drIP18ZB9uU3r2P_DARE

Our YouTube channel (http://europython.eu) has the videos for EuroPython 2011, 2012, 2013 and 2014.
