### ISSUE TITLE
Is search not working currently?

### ISSUE THREAD

**Issue by willingc** [pyvideo/pyvideo#83]
I tried the following searches and received no responses:

http://pyvideo.org/search.html?q=taiwan
http://pyvideo.org/search.html?q=Taiwan

**Comment by zerok** [comment]
I've pinged @ulope about it as the service is running on one of his servers :)

**Comment by ulope** [comment]
Sorry about that. The service had (for some reason) stopped. I've restarted it now and will add some monitoring to have better availability.

**Comment by willingc** [comment]
Thanks @zerok and @ulope for the super quick response. All is searching well now :tada:
