### ISSUE TITLE
PyConArgentina 2014

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#84]
PyConAr videos are up.

* https://www.youtube.com/channel/UCa8tmvBoe5L6BGmRcQHF8qw/videos

Information is here, and here.

* http://myconference.co/pyconar2014/
* http://python.org.ar/Charlas#PyConAr_Rafaela_2014

**Comment by codersquid** [comment]
More videos have been added to their channel and need to be listed on pyvideo.

**Comment by fisadev** [comment]
Hi!
All the videos from the conference are now uploaded to that channel (it took some time and work, but we finished).
Could you include them in the site? :)
