### ISSUE TITLE
rework deployment; update pyvideo to latest richard

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo#87]
Our deployment story is currently a big mess. This is a problem because richard had some big changes lately and we haven't been able to update pyvideo to the new things.

Further, only I have accounts, so only I can update.

Further further, I set it up and the setup is janky.

Further further further, nothing about our current deployment system is repeatable in any way short of someone discovering time travel and looking over past me's shoulder.

This issue covers:

1. create a way to set up a new pyvideo instance that's repeatable and documented
2. create a way to update an existing pyvideo regarding configuration, templates, database and dependency versions

**Comment by willkg** [comment]
This is a stab at item 1, I think: https://github.com/pyvideo/richard-ansible

**Comment by willkg** [comment]
I skimmed richard-ansible and it's interesting. It uses rackspace thingies to set up a new pyvideo box. It covers setting up postgres and some other things.

However, I think I want something more generic than that so that it's possible to use it in other scenarios. e.g. FooConf wants to set up a richard instance for their videos. Someone wants to set up a richard instance for videos related to Pink Marshmallows.

To that end, I think I want a "given a fresh ubuntu 14.04 box with user credentials USER and PWD, set up a richard instance".

**Comment by CarlFK** [comment]
for the current pyvideo install, all we need is the data in the db and some
templates that skin it, right?

if so, then I'll be happy to take a copy of those two things and test that
I can build a new pyvideo using a new deployment




On Thu, Jan 15, 2015 at 8:32 AM, Will Kahn-Greene <notifications@github.com>
wrote:

> I skimmed richard-ansible and it's interesting. It uses rackspace thingies
> to set up a new pyvideo box. It covers setting up postgres and some other
> things.
>
> However, I think I want something more generic than that so that it's
> possible to use it in other scenarios. e.g. FooConf wants to set up a
> richard instance for their videos. Someone wants to set up a richard
> instance for videos related to Pink Marshmallows.
>
> To that end, I think I want a "given a fresh ubuntu 14.04 box with user
> credentials USER and PWD, set up a richard instance".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/87#issuecomment-69976211>.
>



-- 
Carl K

**Comment by codersquid** [comment]
@willkg with the ansible stuff, a user can disregard rackspace and provide an inventory file for hosts that are not on rackspace. I just wanted a way to automate rackspace provisioning. I've been creating those vms by hand. We can have ansible stuff and leave the vm creation as an exercise to the user.

**Comment by codersquid** [comment]
for more deployment examples, here's my experiment with ansible from half a year ago, before the way config changed. It might be more straightforward since I don't use the nginx galaxy role..
  * https://github.com/codersquid/richard-playbook

I've also got a fabric deployment repo, which @CarlFK has used. It's very rudementary.
  *  https://github.com/codersquid/richard-deploy which @CarlFK has used.

**Comment by codersquid** [comment]
status update, I've got https://github.com/pyvideo/richard-ansible working for me. It deploys a simple stack. no haproxy, or whatnot, no elasticsearch, etc. Also, It does not stand up VMs for you.

@willkg we can add more roles as needed.

**Comment by willkg** [comment]
This is done now! pyvideo and dev.pyvideo are both running on the latest richard.
