### ISSUE TITLE
Easy to fix clipping issue

### ISSUE THREAD

**Issue by mdirik** [pyvideo/pyvideo#88]
As stated in description, "PyCon 2009: A Curious Course on Coroutines and Concurrency" part 1 and part 2 in [1]
have some issues regarding the claimed runtime. Some players refuse to play them flat out, some continue to play after the alleged runtime and some play video after audio etc.

Fortunately fixing them is as easy as demuxing & muxing them again with a command like:
`ffmpeg -i 215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.mp4 -vcodec copy -acodec copy 215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.fixed.mp4`

Please consider reuploading them.

I don't know if other videos from the same conference have similar issues but you may also consider checking them if they can be easily fixed too.

[1] http://pyvideo.org/video/213/pycon-2009--a-curious-course-on-coroutines-and-co http://pyvideo.org/video/215/pycon-2009--a-curious-course-on-coroutines-and-c1

**Comment by codersquid** [comment]
@CarlFK do you still have the files for this?

**Comment by mdirik** [comment]
@codersquid FYI, I don't know your workflow but the described solution is still applicable even if the original files aren't available.

**Comment by nadrimajstor** [comment]
I've tried starting with 85GiB dump found at [archive.org] (https://archive.org/details/PyconUsVideos200920102011)
Inside archive was:
* 253M `A Curious Course on Coroutines and Concurrency (Part 001)-1996136.flv`
* 135M `A Curious Course on Coroutines and Concurrency (Part 002)-1995823.flv`
* 71M  `A Curious Course on Coroutines and Concurrency (Part 003)-1995872.flv`

Playing them in vlc shows that _(Part 001)_ covers slides `1-51`, _(Part 002)_ covers slides `109-145` and _(Part 003)_ covers `187-199` so there are missing chunks of substantial size.
However looking at the mp4 files at pyvideo.org looks like the duration is incorrect and applying the workaround provided by OP I could watch for example part 1 well pass 54:07 though vlc will not show progress over 54:07.
Still struggling to repeat mp4 results seen on pyvideo.org using #45 as a guide.

BTW, I don see a valid reason to have a 1GiB mp4 as it is now, where source is 253MiB. :question:

**Comment by nadrimajstor** [comment]
I think I'm seeing the light at the top of the rabbit hole... Using those .flv files from archive.org was a bad start as those are truncated and do not have whole video/audio stream inside them.
Starting with pyvideo.org's mp4 files [Part 1] (http://pyvideo.org/video/213/pycon-2009--a-curious-course-on-coroutines-and-co), [Part 2] (http://pyvideo.org/video/215/pycon-2009--a-curious-course-on-coroutines-and-c1), [Part 3] (http://pyvideo.org/video/214/pycon-2009--a-curious-course-on-coroutines-and-c0)
* 993M `213_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-1-of-3.mp4`
* 996M `215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.mp4`
* 185M `214_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-3-of-3.mp4`

The problem with first two parts are in the last frame where a very large negative value is set for duration. :clap: @elenril for figuring out this little gem

So, lets fix these (by dropping the last frames):
```bash
avconv -i 213_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-1-of-3.mp4 -c copy -frames:v 194661 213_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-1-of-3.fixed.mp4
avconv -i 215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.mp4 -c copy -frames:v 115421 215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.fixed.mp4
```
Now, bring them together:
```bash
avconv -i 213_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-1-of-3.fixed.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts -y part1.ts
avconv -i 215_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-2-of-3.fixed.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts -y part2.ts
avconv -i 214_pycon-2009-a-curious-course-on-coroutines-and-concurrency-part-3-of-3.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts -y part3.ts
avconv -i concat:part1.ts\|part2.ts\|part3.ts -strict experimental pycon-2009-a-curious-course-on-coroutines-and-concurrency.redux.mp4
```
(pretty much the same should be for ffmpeg, it just happens to be I'm using ubuntu 14.04 where libav comes as default)

**Comment by williamsmj** [comment]
A colleague of mine, @nickvermeer, did some work on the audio of this talk too. It was clipping and distorting badly (in between quite clear bits), and generally difficult and exhausting to listen to. The new is much easier on the ears for the duration of a three hour talk! 

The video is available in [this file I put on S3](https://s3.amazonaws.com/pyvideo-beazley/pyvideo-beazley.mp4). If you'd like to use it on pyvideo then please could you download it in the next week or two, so I can remove it from S3?

**Comment by williamsmj** [comment]
I've removed the video from S3. Let me know if you'd like me to reupload it.
