### ISSUE TITLE
Wrong duration PyOhio 2013 - APIs made for mobile networks

### ISSUE THREAD

**Issue by benregn** [pyvideo/pyvideo#89]
The duration states 01:00 but actually is 33:02.

**Comment by CarlFK** [comment]
right.  the 1:00 is what was on the event schedule.  33:02 is what is
correct.
I'm working on this now, but it's only going to apply to things posted in
the future.

On Mon, Feb 16, 2015 at 8:11 AM, Tomas Thor Jonsson <
notifications@github.com> wrote:

> The duration states 01:00 but actually is 33:02.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/89>.
>



-- 
Carl K

**Comment by CarlFK** [comment]
veyepar updated, it will now send the time of the video, not the allocated
time.

Which is the source of this vidoe's error (which I fixed by hand)

On Mon, Feb 16, 2015 at 10:55 AM, Carl Karsten <carl@personnelware.com>
wrote:

> right.  the 1:00 is what was on the event schedule.  33:02 is what is
> correct.
> I'm working on this now, but it's only going to apply to things posted in
> the future.
>
> On Mon, Feb 16, 2015 at 8:11 AM, Tomas Thor Jonsson <
> notifications@github.com> wrote:
>
>> The duration states 01:00 but actually is 33:02.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pyvideo/pyvideo/issues/89>.
>>
>
>
>
> --
> Carl K
>
>


-- 
Carl K

**Comment by benregn** [comment]
:+1:
