### ISSUE TITLE
"Contribute Media" link on homepage is dead

### ISSUE THREAD

**Issue by blha303** [pyvideo/pyvideo#9]
https://github.com/pyvideo/pyvideo/wiki/How-to-Contribute-Media

**Comment by mikeckennedy** [comment]
I want a second that. I have a handful of videos I'd love to submit. Glad to see PyVideo going strong.

**Comment by logston** [comment]
Oh! Thanks for catching this.

**Comment by mikeckennedy** [comment]
Thanks!
