### ISSUE TITLE
404 for PyCon 2017 video

### ISSUE THREAD

**Issue by pya** [pyvideo/pyvideo#90]
This is a dead link:
http://pyvideo.org/pycon-us-2017/kavya-joshi-the-memory-chronicles-a-tale-of-two-pythons-pycon-2017.html

Found by searching for  Kavya Joshi:
http://pyvideo.org/search.html?q=+Kavya+Joshi

This video is available on YouTube:
https://www.youtube.com/watch?v=d7qEzpnkWaY

**Comment by Daniel-at-github** [comment]
The current link is http://pyvideo.org/pycon-us-2017/the-memory-chronicles-a-tale-of-two-pythons.html

**Comment by zerok** [comment]
Ah, we mistook the filename for the slug while the title ends up being the slug. I will try to provide a fix for that in the next couple of days. Please track https://github.com/zerok/pyvideosearch/issues/1 for updates.

**Comment by zerok** [comment]
Should be fixed now :)
