### ISSUE TITLE
Can't browse all videos chronologically?

### ISSUE THREAD

**Issue by cellularmitosis** [pyvideo/pyvideo#90]
Hi,

I can't seem to find a way to just browse all videos chronologically.

There are browse options, but you have to either pick what conference you want to browse videos from (I don't care about that), or what speaker was giving the talk (I don't care about that either).

Help?

**Comment by cellularmitosis** [comment]
(essentially, I want the "Latest videos" feature which is on the home page, but I want more than 10 videos to browse through).

**Comment by codersquid** [comment]
Does this issue sound like what you want? https://github.com/pyvideo/richard/issues/88

**Comment by cellularmitosis** [comment]
That sounds interesting, but is a lot more complicated than just showing
all of the videos sorted by date.

**Comment by codersquid** [comment]
@cellularmitosis right, but that issue will be broken out in to parts, and having a way to browse by date would be a subset of work done on it. Hmm, I am never sure how to handle that type of behavior with github issues. perhaps opening a smaller issue and referring to the big one would be useful. @willkg any comment?

@cellularmitosis if we don't get an issue going for you in a timely fashion could you bump us?

**Comment by cellularmitosis** [comment]
Sure!  Thanks.
