### ISSUE TITLE
switch to richard-ansible

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo#91]
This issue covers using the richard-ansible configuration management stuff to build a new pyvideo server.

This issue covers figuring out requirements and making whatever changes we need to make to this repository and the richard-ansible repository to get there.

Building the new server and migrating data can be covered with a different issue.

**Comment by willkg** [comment]
I'm still working on this, but I think I've got some ideas.

**Comment by codersquid** [comment]
I made the git ref a variable. The way I see things, we would tag releases, and the git ref should refer to a release and not master.

**Comment by willkg** [comment]
Right... So there are two repositories involved in a deployment: richard and pyvideo. I'm not sure where that tag would exist. Would it exist in richard-ansible? Does that mean that everyone using richard-ansible is deploying pyvideo?

**Comment by codersquid** [comment]
btw, :+1: to the convenience script in case I wasn't clear that I like the idea.

Let me make sure I understand your comment about `--extra-vars`.

I would tag everything, and by default richard-ansible would deplay a release of a pyvideo site-repo (to exist) with a default settings module. (unless we make a new site-repo that is simple and generic).

Do you mean that someone would override the the default site-repo (pyvideo) with a ref to their repo, and call something like `make <site git-ref> [<django-settings-module>]?

**Comment by willkg** [comment]
> Let me make sure I understand your comment about --extra-vars.
> 
> I would tag everything, and by default richard-ansible would deplay a release of a pyvideo site-repo (to exist) with a default settings module. (unless we make a new site-repo that is simple and generic).

I think I understand that. I'll fiddle with it and throw together a PR and you can tell me whether I'm close or not.

> Do you mean that someone would override the the default site-repo (pyvideo) with a ref to their repo, and call something like `make []?

I think the default for site-repo should be "no site-specific stuff". For pyvideo, we'd have the value be the pyvideo repo, but we'd store that somehow outside of richard-ansible. Maybe it works to have a settings file we email back and forth or a gist or something.

As a side note, we need an immediate stop-gap fix as well as a long-term solution. I'm trying to think about both at the same time, but we're totally going to do the stop-gap easiest fix possible because we need to get a new system up.

**Comment by willkg** [comment]
I set up a new repository https://github.com/pyvideo/pyvideo-deploy which has the deploy scripts and the briefest documentation possible.

I'll talk with @codersquid about everything we've got so far and we'll figure out what's missing and make sure she can do deploys. In the meantime, I'm going to call this done. Further development will be done in new issues.
