### ISSUE TITLE
Two video frames of same video

### ISSUE THREAD

**Issue by InfiniteBricks** [pyvideo/pyvideo#93]
On the "How the Internet works" page by  Jessica McKellar
PyCon US 2013

There are two of the same video on this page.  

![image](https://user-images.githubusercontent.com/25675821/28991514-ba3e9a68-793d-11e7-9ed7-9d498e37bece.png)

**Comment by InfiniteBricks** [comment]
I see it is pulling the same video from two sources.

**Comment by Daniel-at-github** [comment]
I reopened ti in #94 because I think that the interface is misbehaving.
