### ISSUE TITLE
search box

### ISSUE THREAD

**Issue by posoneto** [pyvideo/pyvideo#93]
search box does not work !

**Comment by willkg** [comment]
Can you be more specific?

**Comment by posoneto** [comment]
I bookmarket the following url: http://pyvideo.org/search?models=videos.video&q=scikit&category=PyCon%20US%202014
and it worked, but now it bring an empty page

**Comment by willkg** [comment]
I updated the index and search is working now. Sorry about that!

**Comment by posoneto** [comment]
Thank you very much willkg, that was a quick response.
I appreciat it.
