### ISSUE TITLE
pycon us 2015 videos

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo#94]
Looks like PyCon US 2015 videos are here:

https://www.youtube.com/channel/UCgxzjK6GuOHVKR_08TT4hJQ

**Comment by codersquid** [comment]
I scraped the channel today and have everything currently there up, http://pyvideo.org/category/65/pycon-us-2015

**Comment by willkg** [comment]
https://us.pycon.org/2015/schedule/presentation/330/

That's missing from the YouTube channel. I don't know offhand what other videos are missing. Maybe they haven't posted everything, yet. We should maybe double-check again next week.

**Comment by codersquid** [comment]
I added the speakerdeck and github repo for slides to the category description, but they are empty right now. I'm guessing they are in the process of making everything available. I will also check this again next week to see if anything is posted. If not, we can remove the links.

**Comment by codersquid** [comment]
Transcripts are getting posted on https://www.dropbox.com/sh/smjar5fxeeeu462/AAB7P3kgFmNramp4DiX6m6hTa?dl=0 and I'm mirroring it at https://archive.org/details/PyconUs2015Captions

Maybe later we can see how to get the stuff in to Amara.
